A `device` is a representation of a breezie tablet. A `device` belongs to a user, so the accessibility is defined
by the user who own the device. This resources have a set of configurations (`settings`) that could alter how they
behave. `Settings` are represented as a sub-resource of `device` in this API.

`StartScreen` is another sub-resource of `device` that represents the configuration of the initial screen on the
 device. This resource is used to manage the apps, bookmarks, categories... that the device will show on its screen.

* <<device-structure, Structure>>
* <<devices-api, devices API>>
** <<resources-device-list, Listing devices>>
** <<resources-device-get, Retrieve a device>>
** <<resources-device-create, Create a device>>
** <<resources-device-update, Replace a device>>
** <<resources-device-patch, Update a device>>
** <<resources-device-delete, Delete a device>>
** <<resources-device-startscreen, Start Screen>>
*** <<resources-device-startscreen-get, Retrieve StartScreen>>
*** <<resources-device-startscreen-put, Update StartScreen>>


[[device-structure]]
==== Structure
include::{device-snippets}/device-get/response-fields.adoc[]

[[devices-api]]
==== Devices API

[[resources-device-list]]
===== Listing devices

A `GET` request to `/devices` will list all devices accessible by the user who make the request.

====== Example request

include::{device-snippets}/device-get-list/curl-request.adoc[]

====== Example response

include::{device-snippets}/device-get-list/http-response.adoc[]

===== Listing devices by Organization

A `GET` request to `/devices/search/findByOrganizationId?id=[organization-id]` will list all the devices belonging
to the organization which identifier is the one passed as a parameter.

====== Example request

include::{device-snippets}/device-get-list-by-organization/curl-request.adoc[]

===== Listing devices by Region

A `GET` request to `/devices/search/findByRegionId?id=[region-id]` will list all the devices belonging
to the region which identifier is the one passed as a parameter.

====== Example request

include::{device-snippets}/device-get-list-by-region/curl-request.adoc[]

===== Listing devices by Campus

A `GET` request to `/devices/search/findByCampusId?id=[campus-id]` will list all the devices belonging
to the campus which identifier is the one passed as a parameter.

====== Example request

include::{device-snippets}/device-get-list-by-campus/curl-request.adoc[]

===== Listing devices by Facility

A `GET` request to `/devices/search/findByFacilityId?id=[facility-id]` will list all the devices belonging
to the facility which identifier is the one passed as a parameter.

====== Example request

include::{device-snippets}/device-get-list-by-facility/curl-request.adoc[]

[[resources-device-get]]
===== Retrieve a Device

A `GET` request to `/devices/{id}` will retrieve the device identified by `id`.

====== Example request

include::{device-snippets}/device-get/curl-request.adoc[]

====== Example response

include::{device-snippets}/device-get/http-response.adoc[]

===== Retrieve device by serialNumber

A `GET` request to `/devices/search/findBySerialNumber?id=[serial-number]` will show the device which serial number is the
one sent as a parameter.

====== Example request

include::{device-snippets}/device-get-list-by-sn/curl-request.adoc[]

===== Retrieve device by Android ID

A `GET` request to `/devices/search/findByAndroidId?id=[android-id]` will show the device which android identifier is the
one sent as a parameter.

====== Example request

include::{device-snippets}/device-get-list-by-androidId/curl-request.adoc[]


[[resources-device-create]]
===== Create a Device

A `POST` request to `/devices` will save a new device and return the created representation.

====== Example request

include::{device-snippets}/device-create/curl-request.adoc[]

====== Example response

include::{device-snippets}/device-create/http-response.adoc[]

[[resources-device-update]]
===== Replace a Device

A `PUT` request to `/devices/{id}` will update the device identified by `id` completely.

====== Example request

include::{device-snippets}/device-put/curl-request.adoc[]

====== Example response

include::{device-snippets}/device-put/http-response.adoc[]

[[resources-device-patch]]
===== Update a Device

A `PUT` request to `/devices/{id}` will update the device identified by `id` partially.

====== Example request

include::{device-snippets}/device-patch/curl-request.adoc[]

====== Example response

include::{device-snippets}/device-patch/http-response.adoc[]

[[resources-device-delete]]
===== DELETE a Device

A `DELETE` request to `/devices/{id}` will delete the device identified by `id`.

====== Example request

include::{device-snippets}/device-delete/curl-request.adoc[]

====== Example response

include::{device-snippets}/device-delete/http-response.adoc[]

[[resources-device-startscreen]]
==== Start Screen
StartScreen resource is composed for two attributes: the maximum number of items that will be displayed
on the device's screen and a sorted list of items candidates to show on the screen. This list of items is
composed by the items `forced` by an admin to be on the start screen, the items manually `settled` on the
screen, the items `promoted` by admins and finally the rest of items candidates to be on the screen.

It is a device job to calculate the items to show in the screen from the information provided in this endpoint.


[[resources-device-startscreen-get]]
===== Retrieve StartScreen
A `GET` request to `/devices/{id}/startscreen` will return the startscreen configuration of the
device identified by `id`.

====== Structure

include::{device-snippets}/startscreen-get/response-fields.adoc[]

====== Example request

include::{device-snippets}/startscreen-get/curl-request.adoc[]

====== Example response

include::{device-snippets}/startscreen-get/http-response.adoc[]


[[resources-device-startscreen-put]]
====== Update StartScreen
A `PUT` request to `/devices/{id}/startscreen` will update the startscreen configuration of the
device identified by `id`.

====== Structure

include::{device-snippets}/startscreen-put/request-fields.adoc[]

====== Example request

include::{device-snippets}/startscreen-put/curl-request.adoc[]

====== Example response

include::{device-snippets}/startscreen-put/http-response.adoc[]


[[resources-profile-sensitive]]
=== Device Settings
`Settings` is a representation of a set of properties that define the device behaviour. `Settings` can be
defined at different levels: breezie level, organization level and user level. Properties defined at
Breezie level can be overwritten at organization and user level and properties set at organization level
can be overwritten at user level.

The set of properties that can be settled to a device are defined in a `schema` that can be found on
`https://api.breezie.com/devices/schema.json`. This json document describes all the properties available and its
restrictions.

* <<settings-api, Settings API>>
** <<resources-settings-retrieve, Retrieve settings for an user >>
** <<resources-settings-update, Replace settings for an user>>
** <<resources-settings-retrieve-by-organization, Retrieve settings for an organization>>
** <<resources-settings-update-by-organization, Replace settings for an organization>>
** <<resources-settings-retrieve-by-breezie, Retrieve settings for all devices>>
** <<resources-settings-update-by-breezie, Replace settings for all devices>>
** <<resources-settings-retrieve-by-device, Retrieve settings for a devices>>
** <<resources-settings-update-by-device, Replace settings for a devices>>


[[settings-api]]
==== Settings API

[[resources-settings-retrieve]]
===== Retrieve settings for a user

A `GET` request to `/users/{id}/settings` will return the set of properties settled at user level.

====== Example request

include::{device-snippets}/user-settings-get/curl-request.adoc[]

====== Example response

include::{device-snippets}/user-settings-get/http-response.adoc[]

[[resources-settings-update]]
===== Replace settings for a user

A `PUT` request to `/users/{id}/settings` will update the set of properties settled at user level.

====== Example request

include::{device-snippets}/user-settings-put/curl-request.adoc[]

====== Example response

include::{device-snippets}/user-settings-put/http-response.adoc[]


[[resources-settings-retrieve-by-organization]]
===== Retrieve settings for an organization

A `GET` request to `/organizations/{id}/settings` will return the set of properties settled at organization level.

====== Example request

include::{device-snippets}/organization-settings-get/curl-request.adoc[]

====== Example response

include::{device-snippets}/organization-settings-get/http-response.adoc[]

[[resources-settings-update-by-organization]]
===== Replace settings for an organization

A `PUT` request to `/organizations/{id}/settings` will update the set of properties settled at organization level. This
properties will be applied for all users inside the organization identified by `id`.

====== Example request

include::{device-snippets}/organization-settings-put/curl-request.adoc[]

====== Example response

include::{device-snippets}/organization-settings-put/http-response.adoc[]


[[resources-settings-retrieve-by-breezie]]
===== Retrieve settings for all devices

A `GET` request to `/breezie-settings` will update the set of properties settled at breezie level.

====== Example request

include::{device-snippets}/breezie-settings-get/curl-request.adoc[]

====== Example response

include::{device-snippets}/breezie-settings-get/http-response.adoc[]

[[resources-settings-update-by-breezie]]
===== Replace settings for all devices

A `PUT` request to `/breezie-settings` will update the set of properties settled at breezie level. This
properties will be applied for all users.

====== Example request

include::{device-snippets}/breezie-settings-put/curl-request.adoc[]

====== Example response

include::{device-snippets}/breezie-settings-put/http-response.adoc[]


[[resources-settings-retrieve-by-device]]
===== Retrieve settings for a devices
A `GET` request to `/devices/{id}/settings` will list all of the the settings applied to a particular device. This settings are a combination of
breezie settings, organizations settings and user settings. In case the same property is defined at different levels, user level
has the highest priority and breezie level the lowest.

====== Example request

include::{device-snippets}/device-settings-get/curl-request.adoc[]

====== Example response

include::{device-snippets}/device-settings-get/http-response.adoc[]


[[resources-settings-update-by-device]]
===== Replace device settings

A `PUT` request to `/devices/{id}/settings` is used to save the device settings. This information cannot be requested from
the API and it is stored to have the knowledge of the status of the device.

====== Example request

include::{device-snippets}/device-settings-put/curl-request.adoc[]

====== Example response

include::{device-snippets}/device-settings-put/http-response.adoc[]
