The Contacts API is used to list, create, read and update contacts. A Contact is a resource saved under a Breezie userRelation's
Account.

In the context of the Breezie client application, contacts appear in the Address Book and depending on configuration,
also on the Start Screen.

The Contact object is very flexible in terms of "validity". This is intentional in design and allows for encompassing
most requirements for contact management that end-users have.

[[resources-contacts-list]]
=== Listing contacts

A `GET` request will list all of the users's contacts.

==== Response structure

include::{google-snippets}/contacts-get-list/response-fields.adoc[]

==== Example request

include::{google-snippets}/contacts-get-list/curl-request.adoc[]

==== Example response

include::{google-snippets}/contacts-get-list/http-response.adoc[]

[[resources-contacts-get]]
=== Retrieve a Contact

A `GET` request will retrieve a contact.

==== Response structure

include::{google-snippets}/contacts-get/response-fields.adoc[]

==== Example request

include::{google-snippets}/contacts-get/curl-request.adoc[]

==== Example response

include::{google-snippets}/contacts-get/http-response.adoc[]


[[resources-contacts-create]]
=== Creating a contact

A `POST` request is used to create a contact. As stated above, the contact object is a very flexible entity, and most
fields are nullable. There are two main constraints:

1) When both `rel` and `label` fields exist in a sub-entity of contact, both may be null however both must not be entered.
 When possible,`rel` should be preferred to `label`, however if there is not a predefined `rel` acceptable for the userRelation,
 `label` acts as a custom value.


2) `rel` will accept values from a pre-determined list. This list changes depending on the sub-entity that `rel` is a part
of. Each of the accepted values are described below in the examples.

==== Request structure

include::{google-snippets}/contacts-create/request-fields.adoc[]

==== Example request

include::{google-snippets}/contacts-create/curl-request.adoc[]

==== Example response

include::{google-snippets}/contacts-create/http-response.adoc[]

[[resources-contacts-update]]
=== Replace a contact

A `PUT` request is used to update a contact. As stated above, the contact object is a very flexible entity, and most
fields are nullable. There are two main constraints:

1) When both `rel` and `label` fields exist in a sub-entity of contact, both may be null however both must not be entered.
 When possible,`rel` should be preferred to `label`, however if there is not a predefined `rel` acceptable for the userRelation,
 `label` acts as a custom value.


2) `rel` will accept values from a pre-determined list. This list changes depending on the sub-entity that `rel` is a part
of. Each of the accepted values are described below in the examples.

==== Request structure

include::{google-snippets}/contacts-put/request-fields.adoc[]

==== Example request

include::{google-snippets}/contacts-put/curl-request.adoc[]

==== Example response

include::{google-snippets}/contacts-put/http-response.adoc[]

[[resources-contacts-delete]]
=== Delete a contact

A `DELETE` request is used to update a contact.

==== Example request

include::{google-snippets}/contacts-delete/curl-request.adoc[]

==== Example response

include::{google-snippets}/contacts-delete/http-response.adoc[]